### ISSUE TITLE
Create section and article

### ISSUE THREAD

**Issue by harunaltunhr** [harunaltunhr/integrate-week2#2]

**Comment by adekimpianna** [comment]
Text for Section and Article (65%, edited)

What is being called a “praline”?  

In semantic terms in the French language, a praline refers to an almond or hazelnut coated confectionery with caramelized sugar. In Belgium, a “praline” is defined by a chocolate candy with a filling. Note that the term “praline” is Belgian in its origin. In France, they talk about small, round chocolates “crotte de chocolat” to describe what the Belgians call pralines. It should be added that there are as many definitions of pralines as there are techniques for making them.  

Pralines are getting modernized

Master chocolate makers continue to improve the recipe, for example adding new flavors such as gianduja, a subtle mixture of toasted dried fruits and white sugar. This praline is in between marzipan due to the white sugar and nut paste with its addition of dried fruit. The little extra is the adding of cocoa butter or chocolate. The ganache version uses crème fraiche and chocolate as well as ingredients such as liqueur, tea or fruit. If you prefer truffles note that this is a sweet mix of butter, melted sugar and chocolate usually accompanied by liqueur. To evaluate the quality of a praline: look at its color, its shine and its consistent shade. Have a look as well if the surface is fine and regular and if it breaks cleanly. As for the smell, it should give off the main flavor followed by the filling before concluding with the taste of chocolate and not of sugar.
